apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://docs.projectcalico.org/v3.17/manifests/calico.yaml
images:
- name: docker.io/calico/cni
  newName: quay.io/vmwcre/calico-cni
- name: docker.io/calico/pod2daemon-flexvol
  newName: quay.io/vmwcre/calico-pod2daemon-flexvol
- name: docker.io/calico/node
  newName: quay.io/vmwcre/calico-node
- name: docker.io/calico/kube-controllers
  newName: quay.io/vmwcre/calico-kube-controllers
