apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/vmware-tanzu/antrea/releases/download/v0.11.1/antrea.yml
images:
- name: antrea/antrea-ubuntu
  newName: quay.io/vmwcre/antrea-ubuntu
