apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/v0.13.0/examples/rbac/cluster-admin.yml
- https://github.com/vmware-tanzu/carvel-kapp-controller/releases/download/v0.13.0/release.yml
- https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/develop/examples/rbac/default-ns.yml
images:
- name: index.docker.io/k14s/kapp-controller
  newName: quay.io/vmwcre/kapp-controller
  newTag: v0.13.0
